# Generated by Django 5.2.6 on 2026-04-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_case_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseactivity',
            name='activity_type',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('priority_change', 'Priority Change'), ('attachment_added', 'Attachment Added'), ('case_created', 'Case Created')], max_length=50),
        ),
    ]
